### ISSUE TITLE
Just published React Heatmap

### ISSUE THREAD

**Issue by JonathanWi** [dmfrancisco/JS.coach#10]
Hey folks!

I just published React Heatmap, a port of heatmap.js for React : 
https://github.com/JonathanWi/react-heatmap

Have a great day,
Cheers

**Comment by dmfrancisco** [comment]
Thank you :+1: I'll make sure this gets included in tomorrow's batch.

**Comment by dmfrancisco** [comment]
This was included today: https://js.coach/react/react-heatmap. Thank you for your contribution :+1:
