### ISSUE TITLE
Add react utlimate resume 

### ISSUE THREAD

**Issue by VincentCtr** [dmfrancisco/JS.coach#1004]
Hello,
I believe the following project should be added for react:
https://github.com/welovedevs/react-ultimate-resume

It is not hosted on npm but it can be used as a boilerplate to create a developer resume.

**Comment by jalalazimi** [comment]
Hello @VincentCtr , Thanks, but unfortunately, we only add hosted packages on NPM.

**Comment by VincentCtr** [comment]
Hello @jalalazimi ,

We added the package on NPM 👍 
https://www.npmjs.com/package/@welovedevs/react-ultimate-resume
