### ISSUE TITLE
react-svg-bubble-slider 😃 😠 😥

### ISSUE THREAD

**Issue by PaulieScanlon** [dmfrancisco/JS.coach#1015]
I believe the following package should be added:
> react-svg-bubble-slider

https://www.npmjs.com/package/react-svg-bubble-slider

react-svg-bubble-slider is fun UI component to help add reactions to your blog posts 😃 😠 😥

**Comment by jalalazimi** [comment]
Thanks 👍 Just added your package here: https://js.coach/package/react-svg-bubble-slider
