### ISSUE TITLE
CKEditor 4 & 5 official integrations

### ISSUE THREAD

**Issue by jacekbogdanski** [dmfrancisco/JS.coach#1017]
I believe the following package should be added:
> ckeditor4-react
> @ckeditor/ckeditor5-react
> @ckeditor/ckeditor5-build-classic
> @ckeditor/ckeditor5-build-inline
> @ckeditor/ckeditor5-build-balloon
> @ckeditor/ckeditor5-build-balloon-block
> @ckeditor/ckeditor5-build-decoupled-document

**Comment by jalalazimi** [comment]
Thanks 👍 Just added your packages here:
https://js.coach/package/ckeditor4-react
https://js.coach/package/@ckeditor/ckeditor5-react
