### ISSUE TITLE
Add react-hoist-hook-class

### ISSUE THREAD

**Issue by x0s3** [dmfrancisco/JS.coach#1020]
I believe the following package should be added:

**react-hoist-hook-class**

This library makes hooks and class interoperability smooth, written in TypeScript, fully typed to ensure each component expects its right props 🎯

(Works with React & React-Native, no external libraries needed 🚀)

Thanks!!

**Comment by jalalazimi** [comment]
Thanks 👍 Just added your package here: https://js.coach/package/react-hoist-hook-class
