### ISSUE TITLE
Add react-native-bigimageviewer

### ISSUE THREAD

**Issue by khalisafkari** [dmfrancisco/JS.coach#1021]
I believe the following package should be added:

> **react-native-bigimageviewer**

react native Big image viewer supporting pan and zoom, with very little memory usage and full featured image loading choices. Powered by Glide

Working with React-Native

Thank you!!

**Comment by jalalazimi** [comment]
Thanks 👍 Just added your package here: https://js.coach/package/react-native-bigimageviewer
