### ISSUE TITLE
add react-native-smaato-ad

### ISSUE THREAD

**Issue by khalisafkari** [dmfrancisco/JS.coach#1022]
I believe the following package should be added:
> react-native-smaato-ad

https://www.npmjs.com/package/react-native-smaato-ad
https://github.com/khalisafkari/react-native-smaato-ad

admob alternative for android users to monetize

**Comment by jalalazimi** [comment]
Hi @khalisafkari, You need to update your Readme. The Readme file is too short.

**Comment by khalisafkari** [comment]
@jalalazimi  I felt that it was too much to write on one page of the readme, so I moved it several pages

**Comment by jalalazimi** [comment]
@khalisafkari, personally I prefer to see the installation guide in the main Readme. and follow the advanced guidance in separate readme. Anyway, we have validations and checking system to evaluate packages. one of the parameters is readme length.

**Comment by khalisafkari** [comment]
@jalalazimi I have made changes to the readme, is it possible this time it will work.

**Comment by jalalazimi** [comment]
@khalisafkari Thanks 👍 Just added your package here: https://js.coach/package/react-native-smaato-ad
