### ISSUE TITLE
react-native-get-shared-prefs

### ISSUE THREAD

**Issue by mCodex** [dmfrancisco/JS.coach#103]
It is a simple module that get all keys & values from Android Shared Preferences.

https://www.npmjs.com/package/react-native-get-shared-prefs

**Comment by mCodex** [comment]
It is a simple module that get all keys from Android Shared Preferences.

**Comment by dmfrancisco** [comment]
Thanks 👍 https://js.coach/react-native/react-native-get-shared-prefs

**Comment by mCodex** [comment]
Hello @dmfrancisco , I'd like to change https://www.npmjs.com/package/react-native-get-shared-prefs to https://www.npmjs.com/package/react-native-sensitive-info is it possible? =)

Thank you!!

**Comment by dmfrancisco** [comment]
Sure, should be good now 👍  https://js.coach/react-native/react-native-sensitive-info
