### ISSUE TITLE
react-native-alt-demo

### ISSUE THREAD

**Issue by dusnoki** [dmfrancisco/JS.coach#106]

**Comment by dmfrancisco** [comment]
Is this the name of the NPM package? I can't find it in the repository: https://www.npmjs.com/package/react-native-alt-demo

**Comment by dusnoki** [comment]
It's a name of a github repo. The only react native altjs demo i could find.

**Comment by dusnoki** [comment]
https://github.com/mrblueblue/react-native-alt-demo

**Comment by dmfrancisco** [comment]
Thanks! Unfortunately we can't add it to the catalog until it has been published to NPM.

**Comment by dmfrancisco** [comment]
I'll close this issue for now. Still, thanks for taking the time to share this 👍
