### ISSUE TITLE
react-native-transformable-image

### ISSUE THREAD

**Issue by ldn0x7dc** [dmfrancisco/JS.coach#127]
A transformable image component, as the known PhotoView or ImageViewer, supports gestures like pan, pinch, double tab and fling, is written in pure JavaScript, supports both iOS and Android.
Check [here](https://github.com/yoaicom/react-native-transformable-image)

**Comment by dmfrancisco** [comment]
Thanks! 👍  https://js.coach/react-native/react-native-transformable-image
