### ISSUE TITLE
react-omnislider and react-color-picker

### ISSUE THREAD

**Issue by 3stacks** [dmfrancisco/JS.coach#130]
https://www.npmjs.com/package/@lukeboyle/react-omnislider
https://www.npmjs.com/package/@lukeboyle/react-color-picker

Made by [lukeboyle](http://lukeboyle.com)

**Comment by dmfrancisco** [comment]
Thanks for your contribution but unfortunately, due to limitations with the NPM API, we can't add scoped packages to our catalog right now 😞

**Comment by 3stacks** [comment]
Oh no :(

According to someone from npm their stats system doesn't work with scoped packages either, so hopefully they're working on ironing that out.

Thanks anyway mate.

**Comment by dmfrancisco** [comment]
No problem! Thanks again 👍

**Comment by dmfrancisco** [comment]
Hello @3stacks! I know this was more than 1 year ago, but just wanted to let you know that scoped packages are supported now and I just added your packages:

https://js.coach/react/@lukeboyle-react-omnislider
https://js.coach/react/@lukeboyle-react-color-picker

**Comment by 3stacks** [comment]
Thanks @dmfrancisco, I totally forgot about this. Glad you're keeping track of things :)
