### ISSUE TITLE
react-router-native

### ISSUE THREAD

**Issue by jmurzy** [dmfrancisco/JS.coach#134]
react-router-native [[npm]](https://www.npmjs.com/package/react-router-native)

From the README:

> React Router community decided that a [reducer-based paradigm](https://github.com/reactjs/react-router/issues/743) similar to that of **NavigationExperimental** is better suited to native navigation. Transition to a reducer-based paradigm is also being [discussed](https://github.com/reactjs/react-router/issues/3190) for the web. On the other hand, NavigationExperimental [has no intention to support ](https://github.com/ericvicenti/navigation-rfc/issues/64#issuecomment-209001717) a React Router-like interface and leaves the navigation state up to the developer to maintain.
> 
> A declarative API removes the need to write [boilerplate code](https://github.com/facebook/react-native/commit/1dc33b5f23640a60682ac879b9a3e94a4aa519d9) and speeds up development. React Router Native follows React's **Learn Once, Write Anywhere** principle by providing a superset of React Router's API that marries _React Router_ to _NavigationExperimental_.

Thanks!

🍺

**Comment by dmfrancisco** [comment]
Thanks! 👍  https://js.coach/react-native/react-router-native
