### ISSUE TITLE
react-portql is missing

### ISSUE THREAD

**Issue by vinej** [dmfrancisco/JS.coach#139]
this package is missing

https://github.com/vinej/react-portal

Thanks

**Comment by dmfrancisco** [comment]
Thank you for your contribution 👍  Is this available in the NPM public registry?
We have [`react-portal`](https://npmjs.com/react-portal) but seems to be a different package.

**Comment by vinej** [comment]
I don't know about the NPM public registry. This is a public git with MIT licence.

Thanks

**Comment by dmfrancisco** [comment]
Thanks @vinej, but unfortunately we currently can't list packages that are not published in NPM.
