### ISSUE TITLE
react-native-view-pager

### ISSUE THREAD

**Issue by ldn0x7dc** [dmfrancisco/JS.coach#144]
https://github.com/ldn0x7dc/react-native-view-pager
https://www.npmjs.com/package/@ldn0x7dc/react-native-view-pager
**Pls notice that this module is scoped under @ldn0xd7c because the name has already been taken**

**Comment by dmfrancisco** [comment]
Hello @ldn0x7dc, thank you for your contribution 👍 Unfortunately we are currently unable to include scoped packages. This is related to a limitation with the NPM API.
