### ISSUE TITLE
react-auto-header-list & react-universal-saga

### ISSUE THREAD

**Issue by xkawi** [dmfrancisco/JS.coach#172]
https://github.com/xkawi/react-auto-header-list
https://www.npmjs.com/package/react-auto-header-list

https://github.com/xkawi/react-universal-saga
https://www.npmjs.com/package/react-universal-saga

**Comment by dmfrancisco** [comment]
Thanks 👍 
https://js.coach/react/react-auto-header-list
https://js.coach/react/react-universal-saga
