### ISSUE TITLE
Some components

### ISSUE THREAD

**Issue by willianjusten** [dmfrancisco/JS.coach#173]
### Lyef Pokemon

[https://github.com/lyef/lyef-pokemon](https://github.com/lyef/lyef-pokemon)
[https://www.npmjs.com/package/lyef-pokemon](https://www.npmjs.com/package/lyef-pokemon)
### Lyef Flags

[https://github.com/lyef/lyef-flags](https://github.com/lyef/lyef-flags)
[https://www.npmjs.com/package/lyef-flags](https://www.npmjs.com/package/lyef-flags)
### Lyef Switch Button

[https://github.com/lyef/lyef-switch-button](https://github.com/lyef/lyef-switch-button)
[https://www.npmjs.com/package/lyef-switch-button](https://www.npmjs.com/package/lyef-switch-button)

**Comment by dmfrancisco** [comment]
Thanks 👍 
https://js.coach/react/lyef-pokemon
https://js.coach/react/lyef-flags
https://js.coach/react/lyef-switch-button
