### ISSUE TITLE
TextInputLayout for react-native works on both android and ios

### ISSUE THREAD

**Issue by zbtang** [dmfrancisco/JS.coach#178]
Could you help add this to js.coach? Thanks!

https://github.com/zbtang/React-Native-TextInputLayout
![preview](https://raw.githubusercontent.com/zbtang/React-Native-TextInputLayout/master/art/demo.gif)

**Comment by dmfrancisco** [comment]
Thanks 👍  https://js.coach/react-native/rn-textinputlayout
