### ISSUE TITLE
'View on Github' open in new tab

### ISSUE THREAD

**Issue by Bhullnatik** [dmfrancisco/JS.coach#18]
Would it be possible for the button 'View on Github' to open the Github repository in another tab? The readme integration is great, but sometimes I want to check out more about a project and I'm always caught off guard because I'm not done navigating on js.coach but my current tab ends up being replaced. My concern is the same for the links in the README.

I understand that this may be subjective of course.

Thanks for your project!

**Comment by dmfrancisco** [comment]
Hey @Bhullnatik! There's actually an open PR that does exactly that.

Personally I'm not a fan of `target="_blank"`, because I'm so used to `cmd+click` that I prefer to always have that control. When a link has `target="_blank"`, there isn't a way for the user to open the link in the same tab.

**Comment by Bhullnatik** [comment]
Oh sorry I checked the issues but forgot to check PRs. Will close this issue.
I'm used to `cmd+click` too, but strangely for me when I'm browsing js.coach it's more like shopping aimlessly, so I'm resting on my hand, or doing something else and reaching `cmd` becomes hard, but I'll put that under gymnastic I have to do.
I agree with you on `target="_blank"`, might not be the best solution so that the user still has the choice.

**Comment by dmfrancisco** [comment]
No worries! I'll ask some people and do some research as soon as possible. Since "View on GitHub" is clearly an external link, I guess people understand if we default to opening in another tab.

And thank you for your suggestion :+1:
