### ISSUE TITLE
Please add react native material design searchbar

### ISSUE THREAD

**Issue by ananddayalan** [dmfrancisco/JS.coach#180]
Please add npm package react-native-material-design-searchbar
https://www.npmjs.com/package/react-native-material-design-searchbar
https://github.com/ananddayalan/react-native-material-design-searchbar

**Comment by dmfrancisco** [comment]
Thanks 👍  https://js.coach/react-native/react-native-onback

**Comment by dmfrancisco** [comment]
Thanks 👍  https://js.coach/react-native/react-native-material-design-searchbar
