### ISSUE TITLE
Fixed-Data-Table should be replaced

### ISSUE THREAD

**Issue by ryan-hamblin** [dmfrancisco/JS.coach#190]
The package "Fixed-Data-Table" is no longer maintained by the FB team and could be considered to be replaced with "Fixed-Data-Table-2" http://schrodinger.github.io/fixed-data-table-2/ as there is a company actively maintaining the package.

**Comment by dmfrancisco** [comment]
Thanks 👍 I added [`fixed-data-table-2`](https://js.coach/react/fixed-data-table-2) and will consider removing `fixed-data-table` in the future.
