### ISSUE TITLE
react-native-spotify

### ISSUE THREAD

**Issue by viestat** [dmfrancisco/JS.coach#191]
A native module that allows you to use the Spotify SDK API (IOS) with JavaScript through react-native. 
[GitHub repo.](https://github.com/viestat/react-native-spotify)
[npm packacge.](https://www.npmjs.com/package/react-native-spotify)

**Comment by dmfrancisco** [comment]
Thanks! 👍 https://js.coach/react-native/react-native-spotify
Sorry for taking so long, for some reason I had some troubles downloading data for this one.
