### ISSUE TITLE
floating label and round checkbox for RN

### ISSUE THREAD

**Issue by vonovak** [dmfrancisco/JS.coach#193]
1. round iOS-styled checkbox 
   https://github.com/vonovak/react-native-round-checkbox
   https://www.npmjs.com/package/rn-round-checkbox
2. floating label 
   https://github.com/vonovak/react-native-flabel-textfield
   https://www.npmjs.com/package/rn-flabel-textfield

thanks!!

**Comment by dmfrancisco** [comment]
Thanks 👍 
https://js.coach/react-native/rn-round-checkbox
https://js.coach/react-native/rn-flabel-textfield
