### ISSUE TITLE
off canvas menu component for react native

### ISSUE THREAD

**Issue by proshoumma** [dmfrancisco/JS.coach#194]
Some beautifully crafted off canvas menu components for react native applications.
[GitHub Repo](https://github.com/shoumma/react-native-off-canvas-menu)
[NPM Package](https://www.npmjs.com/package/react-native-off-canvas-menu)

**Comment by dmfrancisco** [comment]
Thanks 👍 https://js.coach/react-native/react-native-off-canvas-menu
