### ISSUE TITLE
How to submit new components?

### ISSUE THREAD

**Issue by ahmed1490** [dmfrancisco/JS.coach#2]
Is there a way for the public to contribute?

**Comment by dmfrancisco** [comment]
Hello @ahmed1490. The process is now a lot more automatic, but there are still some cases where packages are incorrectly rejected. So I'm thinking of adding a form to the site or simply ask contributors to open new issues.

**Comment by ahmed1490** [comment]
Cool! A form will help very much.
Also a place where rejected packages are mentioned can help too. :)

Thanks for the amazing work! :100:
