### ISSUE TITLE
Input masks

### ISSUE THREAD

**Issue by msafi** [dmfrancisco/JS.coach#206]
Hi,

I'd like to suggest the following input mask libraries:
- [react-text-mask](https://www.npmjs.com/package/react-text-mask)
- [angular2-text-mask](https://www.npmjs.com/package/angular2-text-mask)
- [ember-text-mask](https://www.npmjs.com/package/ember-text-mask)
- [vanilla-text-mask](https://www.npmjs.com/package/vanilla-text-mask)

They're part of my input mask library [Text Mask](https://github.com/text-mask/text-mask).

Thanks so much for your consideration and the work you're putting into this!

**Comment by dmfrancisco** [comment]
Thanks 👍 
https://js.coach/react/react-text-mask
https://js.coach/all/angular2-text-mask
