### ISSUE TITLE
Add Image Zoomer Component 

### ISSUE THREAD

**Issue by endigo** [dmfrancisco/JS.coach#21]
https://github.com/ENDiGo/react-image-zoomer

**Comment by dmfrancisco** [comment]
Hey @ENDiGo! The package must also be published on NPM. Let me know when you're done :+1:

**Comment by ENDiGo** [comment]
@dmfrancisco It's done.
Here is url: https://www.npmjs.com/package/react-image-zoomer
Thanks you

**Comment by dmfrancisco** [comment]
Thank you @ENDiGo :+1: https://js.coach/react/react-image-zoomer
