### ISSUE TITLE
A React Native Percentage Component

### ISSUE THREAD

**Issue by JackPu** [dmfrancisco/JS.coach#210]
Please view it here:

GIithub: https://github.com/JackPu/react-native-percentage-circle

NPM: https://www.npmjs.com/package/react-native-percentage-circle
 It is a component which supports you define your percent and draw the circle.And also you can use it as a progress bar.

😄😄😄💐💐。
**Screenshot**:

![image](https://cloud.githubusercontent.com/assets/4744967/18089113/d6ffcf94-6ef0-11e6-9375-22e77515e02d.png)

**Comment by dmfrancisco** [comment]
Thanks 👍  https://js.coach/react-native/react-native-percentage-circle
