### ISSUE TITLE
rn-stack-router

### ISSUE THREAD

**Issue by sarriaroman** [dmfrancisco/JS.coach#227]
https://github.com/sarriaroman/rn-stack-router

**Comment by dmfrancisco** [comment]
Hi @sarriaroman! Can you publish your package on the NPM registry?

**Comment by sarriaroman** [comment]
Hi @dmfrancisco published!. Thanks!

**Comment by dmfrancisco** [comment]
Thanks :+1: Sorry about the delay! https://js.coach/react-native/rn-stack-router
