### ISSUE TITLE
react-native-segmented-control-tab

### ISSUE THREAD

**Issue by kirankalyan5** [dmfrancisco/JS.coach#244]
Custom React native component similar to SegmentedControlIOS, primarily built to support both IOS and Android.

Github Link: https://github.com/kirankalyan5/react-native-segmented-control-tab
npm link: https://www.npmjs.com/package/react-native-segmented-control-tab

Thanks

**Comment by dmfrancisco** [comment]
Thanks 👍 https://js.coach/react-native/react-native-segmented-control-tab
