### ISSUE TITLE
storybook-addon-material-ui

### ISSUE THREAD

**Issue by usulpro** [dmfrancisco/JS.coach#256]
Addon for [storybook](https://github.com/kadirahq/react-storybook) wich wrap [material-ui components](http://www.material-ui.com/) into MuiThemeProvider. This helps and simplifies development of material-ui based components.

npm: https://www.npmjs.com/package/storybook-addon-material-ui
github: https://github.com/sm-react/storybook-addon-material-ui

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/storybook-addon-material-ui
