### ISSUE TITLE
storybook-addon-knobs

### ISSUE THREAD

**Issue by mbonaci** [dmfrancisco/JS.coach#260]

**Comment by dmfrancisco** [comment]
Thanks for your contribution! Is [this the package](https://github.com/kadirahq/storybook-addon-knobs)? It seems to be scoped (the name is `@kadira/storybook-addon-knobs`) so currently I'm unable to add it to the catalog 😕

**Comment by mbonaci** [comment]
Maybe that's obvious for others, but can you explain (perhaps in `CONTRIBUTING.md`) why scoped packages cannot be added?
Thx

**Comment by dmfrancisco** [comment]
When I first implemented the code, the API didn't return any results for scoped packages. They also didn't appear in the search results in the NPM website, but that has changed. So maybe the API changed too. I'll have to take a look 😃 I'll add to the backlog!
