### ISSUE TITLE
add a new component react-core-image-upload

### ISSUE THREAD

**Issue by JackPu** [dmfrancisco/JS.coach#283]
I submit a new component for image to upload and crop.

npm:[react-core-image-upload](https://www.npmjs.com/package/react-core-image-upload)

Github: [react-core-image-upload](https://github.com/Vanthink-UED/react-core-image-upload)

[Demo](http://vanthink-ued.github.io/react-core-image-upload/upload.html)

Hope it help us. 😊💐

**Comment by dmfrancisco** [comment]
Thanks! :+1:🌷  https://js.coach/react/react-core-image-upload
