### ISSUE TITLE
React-Native: show 'Windows' platform in summary, not just 'iOS' and 'Android', and allow filtering by 'Windows'

### ISSUE THREAD

**Issue by jmcginty** [dmfrancisco/JS.coach#290]
react-native runs on many platforms, and a growing number of react-native components support Windows as a platform via [react-native-windows](https://github.com/ReactWindows/react-native-windows), e.g. [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons).

**Comment by dmfrancisco** [comment]
Thank you for your suggestion 🙌   Sorry for taking so long, I finally added a filter for react native components that support Windows.

**Comment by jmcginty** [comment]
That's great ! 👍
