### ISSUE TITLE
Add react-native-appboy-sdk

### ISSUE THREAD

**Issue by briancaw** [dmfrancisco/JS.coach#30]
Found here: https://www.npmjs.com/package/react-native-appboy-sdk

Thanks!

**Comment by dmfrancisco** [comment]
Can you also provide the link to the GitHub repository? It seems [the link shown in NPM](https://github.com/Appboy/appboy-react-sdk) returns 404.

**Comment by briancaw** [comment]
Apologies for that, it's the right link but I had to update the settings.

https://github.com/Appboy/appboy-react-sdk

Thanks again.

**Comment by dmfrancisco** [comment]
Done! Thank you :+1: https://js.coach/react-native/react-native-appboy-sdk
