### ISSUE TITLE
Please add react-native-webbrowser (iOS + Android)

### ISSUE THREAD

**Issue by d-a-n** [dmfrancisco/JS.coach#31]
A cross-platform (iOS / Android), full-featured in-app web browser component for React Native that is highly customizable. Currently you can hide the address-, status- and toolbar. Additionally the foreground and background colors can be modified.

https://www.npmjs.com/package/react-native-webbrowser
https://github.com/d-a-n/react-native-webbrowser

**Comment by dmfrancisco** [comment]
Done! Thank you again @d-a-n :+1: https://js.coach/react-native/react-native-webbrowser
