### ISSUE TITLE
react-native-periodic

### ISSUE THREAD

**Issue by lorensr** [dmfrancisco/JS.coach#316]
Is the fact that it's not automatically in the JS.coach results due to a missing npm keyword? Great site, thanks! 😊

**Comment by dmfrancisco** [comment]
Thanks 👍 https://js.coach/react-native/react-native-periodic

The package was picked up automatically but I manually review the list before publishing, just to make sure descriptions look nice, and recently have been more busy and/or lazy 😛

Sorry for the delay!
