### ISSUE TITLE
React-core-loading-spinner 

### ISSUE THREAD

**Issue by JackPu** [dmfrancisco/JS.coach#318]
![image](https://cloud.githubusercontent.com/assets/4744967/20831606/b940b968-b8c0-11e6-9aa7-f58c36037dd2.png)

a component for loading spinner

GitHub ： https://github.com/JackPu/react-core-loading-spinner

npm : https://www.npmjs.com/package/react-core-loading-spinner

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/react-core-loading-spinner
