### ISSUE TITLE
Please add react-native-modal-picker

### ISSUE THREAD

**Issue by d-a-n** [dmfrancisco/JS.coach#32]
A cross-platform (iOS / Android) selector/picker component for React Native that is highly customizable and supports sections.

https://www.npmjs.com/package/react-native-modal-picker
https://github.com/d-a-n/react-native-modal-picker

**Comment by dmfrancisco** [comment]
Thanks @d-a-n :+1: https://js.coach/react-native/react-native-modal-picker
