### ISSUE TITLE
Please add flow-status-webpack-plugin

### ISSUE THREAD

**Issue by diegodurli** [dmfrancisco/JS.coach#33]
This plugin will run Flow (Flowtype.org) Status on each Webpack build.

https://github.com/diegodurli/flow-status-webpack-plugin
https://www.npmjs.com/package/flow-status-webpack-plugin

Thank you!

**Comment by dmfrancisco** [comment]
Thanks @diegodurli :+1: https://js.coach/webpack/flow-status-webpack-plugin
