### ISSUE TITLE
react-fuzzy-picker

### ISSUE THREAD

**Issue by 1egoman** [dmfrancisco/JS.coach#337]
React Fuzzy Picker is a component that implements a fuzzy finder similar to Sublime Text's command palette or Slack's channel switcher. Here's it in action:

![image](https://raw.githubusercontent.com/1egoman/fuzzy-picker/master/assets/example.gif)

https://www.npmjs.com/package/react-fuzzy-picker

Thanks!

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/react-fuzzy-picker
