### ISSUE TITLE
Adding react-yearly-calendar

### ISSUE THREAD

**Issue by GiovanniFrigo** [dmfrancisco/JS.coach#35]
This component was listed in react.parts but is currently missing from js.coach. Can you add it back?

name **react-yearly calendar**
repo https://github.com/BelkaLab/react-yearly-calendar
npm: https://www.npmjs.com/package/react-yearly-calendar

Thanks!

**Comment by dmfrancisco** [comment]
It was marked as a fork, and that's why it wasn't listed. In this case, it definitely makes sense to add it to the catalog. Thanks! :+1: https://js.coach/react/react-yearly-calendar

**Comment by GiovanniFrigo** [comment]
Thanks!
