### ISSUE TITLE
react-strapmenu

### ISSUE THREAD

**Issue by sercanov** [dmfrancisco/JS.coach#357]
🐱 https://github.com/sercanov/react-strapmenu
📦 https://www.npmjs.com/package/react-strapmenu

**Comment by sercanov** [comment]
you don't like it ? :) @dmfrancisco

**Comment by dmfrancisco** [comment]
I do, and thanks :+1: https://js.coach/react/react-strapmenu

Sorry for taking such a long time! There was an issue that prevented me from accepting and updating some packages 😕
