### ISSUE TITLE
react-lazy-tree

### ISSUE THREAD

**Issue by ethanselzer** [dmfrancisco/JS.coach#373]
Please consider react-lazy-tree.

Github: https://github.com/ethanselzer/react-lazy-tree
NPM: https://www.npmjs.com/package/react-lazy-tree
Demo Site: https://ethanselzer.github.io/react-lazy-tree

Thanks!

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/react-lazy-tree
