### ISSUE TITLE
react-native-smart-camera-roll-picker

### ISSUE THREAD

**Issue by cyqresig** [dmfrancisco/JS.coach#376]
https://www.npmjs.com/package/react-native-smart-camera-roll-picker
https://github.com/react-native-component/react-native-smart-camera-roll-picker

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-smart-camera-roll-picker

Sorry for taking so long! There was an issue that prevented me from accepting and updating some packages.
