### ISSUE TITLE
react-native-simple-table

### ISSUE THREAD

**Issue by Jeepeng** [dmfrancisco/JS.coach#384]
npm:  [https://www.npmjs.com/package/react-native-simple-table](https://www.npmjs.com/package/react-native-simple-table)
github:  [https://github.com/Jeepeng/react-native-simple-table](https://github.com/Jeepeng/react-native-simple-table)

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-simple-table
