### ISSUE TITLE
Update react-native-swipeout repo to maintained version

### ISSUE THREAD

**Issue by JulianKingman** [dmfrancisco/JS.coach#387]
Maintained version is here: https://github.com/silentcloud/react-native-swipeout

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-swipeout

Sorry for taking so long! There was an issue that prevented me from accepting and updating some packages.

**Comment by JulianKingman** [comment]
lol, bad timing, silentcloud just became a maintainer for the original so now his fork is deprecated

**Comment by JulianKingman** [comment]
Anyway, it looks like it's still right.
