### ISSUE TITLE
react-native-stars

### ISSUE THREAD

**Issue by 4umo** [dmfrancisco/JS.coach#390]
![rn-stars](https://cloud.githubusercontent.com/assets/9997548/22914360/0f69f5d2-f23e-11e6-82a5-ce0a4986d611.gif)

https://github.com/Extrct/react-native-stars
https://www.npmjs.com/package/react-native-stars

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-stars

Sorry for taking so long! There was an issue that prevented me from accepting and updating some packages.

**Comment by Extrct** [comment]
no prob, thanks for accepting it and keep up the awesome work with JS Coach!
