### ISSUE TITLE
react-native-nuance-text-to-speech

### ISSUE THREAD

**Issue by simdonl** [dmfrancisco/JS.coach#391]
A simple plugin to add text to speech functionality to your React Native app, with the use of Nuance speechkit.

https://github.com/simdonl/react-native-nuance-text-to-speech
https://www.npmjs.com/package/react-native-nuance-text-to-speech

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-nuance-text-to-speech
