### ISSUE TITLE
react-native-animated-sprite

### ISSUE THREAD

**Issue by micahrye** [dmfrancisco/JS.coach#392]
react-native-animated-sprite (RNAS) package is a feature rich declarative component for animation, tweening, and dragging sprites. Animation is achieved using frame-by-frame animation, tweening uses the React Native Animated class, and dragging uses React Native PanResponder.

https://github.com/micahrye/react-native-animated-sprite
https://www.npmjs.com/package/react-native-animated-sprite

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-animated-sprite

Sorry for taking so long! There was an issue that prevented me from accepting and updating some packages.
