### ISSUE TITLE
Please add flexicious-react-datagrid

### ISSUE THREAD

**Issue by flexicious** [dmfrancisco/JS.coach#407]
Here is a Enterprise grade pure React DataGrid component that I think will be very helpful for folks who write business applications in React. [http://www.reactdatagrid.com/](http://www.reactdatagrid.com/)

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/flexicious-react-datagrid

Sorry for taking so long! There was an issue that prevented me from accepting and updating some packages.
