### ISSUE TITLE
react-native-material-dialog

### ISSUE THREAD

**Issue by hectahertz** [dmfrancisco/JS.coach#409]
Please consider react-native-material-dialog

https://github.com/hectahertz/react-native-material-dialog
https://www.npmjs.com/package/react-native-material-dialog

Thanks!

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-material-dialog

Sorry for taking so long! There was an issue that prevented me from accepting and updating some packages.
