### ISSUE TITLE
generator-rn-toolbox

### ISSUE THREAD

**Issue by Almouro** [dmfrancisco/JS.coach#420]
https://www.npmjs.com/package/generator-rn-toolbox

Disclaimer: I'm one of the contributors of this package.

It's a neat set of generators to setup cool stuff for your React Native project, like automatic [asset generation](https://github.com/bamlab/generator-rn-toolbox/blob/master/generators/assets/README.md) or automatic Fastlane setup.

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/generator-rn-toolbox
