### ISSUE TITLE
react-native-apex-ui

### ISSUE THREAD

**Issue by linjinyi** [dmfrancisco/JS.coach#425]
### A react native cross platform ui kit.

github: [https://github.com/glinjy/react-native-apex-ui](https://github.com/glinjy/react-native-apex-ui)
npm: [https://www.npmjs.com/package/react-native-apex-ui](https://www.npmjs.com/package/react-native-apex-ui)

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-apex-ui

Sorry for taking so long! There was an issue that prevented me from accepting and updating some packages.
