### ISSUE TITLE
react-nest-thermostat

### ISSUE THREAD

**Issue by KevinMellott91** [dmfrancisco/JS.coach#43]
I created a React component that represents the display of a Nest thermostat. Please feel free to add if you feel it is appropriate.

[https://github.com/KevinMellott91/react-nest-thermostat](https://github.com/KevinMellott91/react-nest-thermostat)

I've created a [live demo](https://run.plnkr.co/plunks/SYkIZmFFL8tCHnTHMGJY/) of the behavior as well.

**Comment by dmfrancisco** [comment]
Thanks! :+1: https://js.coach/react/react-nest-thermostat

**Comment by KevinMellott91** [comment]
Thanks!
