### ISSUE TITLE
React-impressJS

### ISSUE THREAD

**Issue by GeorgioWan** [dmfrancisco/JS.coach#432]
**React-impressJS** is a presentation framework based on [impress.js](https://github.com/impress/impress.js), it operates elements with Virtual DOM but not DOM, provides the better way to implement impress.js.

Here is [**source**](https://github.com/GeorgioWan/react-impressjs) & [**demo**](https://oawan.me/react-impressjs)
[![NPM install](https://nodei.co/npm/react-impressjs.png)](https://www.npmjs.com/package/react-impressjs)

Thanks for all.

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/react-impressjs

Sorry for taking so long! There was an issue that prevented me from accepting and updating some packages.
