### ISSUE TITLE
reactjs-percentage-circle

### ISSUE THREAD

**Issue by JackPu** [dmfrancisco/JS.coach#434]
[reactjs-percentage-circle](https://github.com/JackPu/reactjs-percentage-circle) is a component for ReactJS to show a percentage circle when you specify a percent number.

[npm here](https://www.npmjs.com/package/reactjs-percentage-circle)

``` bash
npm i reactjs-percentage-circle --save
```

Hope u can add it 😝💐.

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/reactjs-percentage-circle
