### ISSUE TITLE
[Request] Add react-datepicker2

### ISSUE THREAD

**Issue by mberneti** [dmfrancisco/JS.coach#437]
Library name: react-datepicker2
Git repository url: https://github.com/mberneti/react-datepicker2
npm package url(optional): https://www.npmjs.com/package/react-datepicker2
License(s): MIT
Official homepage: https://mberneti.github.io/react-datepicker2/

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/react-datepicker2

Sorry for taking so long! There was an issue that prevented me from accepting and updating some packages.
