### ISSUE TITLE
react-tabs-component

### ISSUE THREAD

**Issue by jacklam718** [dmfrancisco/JS.coach#449]
github: https://github.com/jacklam718/react-tabs-component
npm: https://www.npmjs.com/package/rt-tabs-component

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/react-tabs-component

**Comment by jacklam718** [comment]
@dmfrancisco `https://js.coach/react/react-tabs-component` this wrong link

**Comment by dmfrancisco** [comment]
@jacklam718 Oops! Sorry about that. Here's the right one: https://js.coach/react/rt-tabs-component
Thanks!

**Comment by jacklam718** [comment]
@dmfrancisco thanks
