### ISSUE TITLE
async-reactor

### ISSUE THREAD

**Issue by xtuc** [dmfrancisco/JS.coach#455]
https://www.npmjs.com/package/async-reactor

Thanks,
Sven

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/async-reactor

**Comment by xtuc** [comment]
Awesome, thanks!

Would this be automatically tweeted?

**Comment by dmfrancisco** [comment]
@xtuc Yes, it wasn't tweeted yet but will be :)
