### ISSUE TITLE
react-native-customizable-actionsheet

### ISSUE THREAD

**Issue by lxfriday** [dmfrancisco/JS.coach#456]
[https://github.com/lxfriday/react-native-customizable-actionsheet](https://github.com/lxfriday/react-native-customizable-actionsheet)
[https://www.npmjs.com/package/react-native-customizable-actionsheet](https://www.npmjs.com/package/react-native-customizable-actionsheet)

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-customizable-actionsheet
