### ISSUE TITLE
react-simple-chatbot

### ISSUE THREAD

**Issue by LucasBassetti** [dmfrancisco/JS.coach#461]
github: [https://github.com/LucasBassetti/react-simple-chatbot](https://github.com/LucasBassetti/react-simple-chatbot)
npm: [https://www.npmjs.com/package/react-simple-chatbot](https://www.npmjs.com/package/react-simple-chatbot)
site: [https://github.com/LucasBassetti/react-simple-chatbot](http://lucasbassetti.com.br/react-simple-chatbot/)

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/react-simple-chatbot
