### ISSUE TITLE
react native responsive grid

### ISSUE THREAD

**Issue by idibidiart** [dmfrancisco/JS.coach#462]
https://github.com/idibidiart/react-native-responsive-grid

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-responsive-grid

**Comment by idibidiart** [comment]
@dmfrancisco unfortunately i submitted that a bit too early in the process. The API has been finalized now and it introduces breaking changes. I noticed that you have a static snapshot of the Readme. If you could update that it would be great. I don't expect to make any changes the readme or the API at this point. Thanks very much. I like js.coach!

**Comment by dmfrancisco** [comment]
@idibidiart No problem! The readmes are updated automatically, but sometimes it takes a long time, so I just forced an update manually. Should be good now!
