### ISSUE TITLE
react-native-parallax-scroll

### ISSUE THREAD

**Issue by z4o4z** [dmfrancisco/JS.coach#479]
NPM: https://www.npmjs.com/package/react-native-parallax-scroll
Github: https://github.com/z4o4z/react-native-parallax-scroll

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-parallax-scroll

**Comment by z4o4z** [comment]
Hi @dmfrancisco the package was moved to 

https://github.com/monterosalondon/react-native-parallax-scroll
https://www.npmjs.com/package/@monterosa/react-native-parallax-scroll

**Comment by dmfrancisco** [comment]
We now support scoped packages, so I updated the entry accordingly. You can see it here: https://js.coach/react-native/@monterosa-react-native-parallax-scroll Thanks!
