### ISSUE TITLE
react-virtual-slider

### ISSUE THREAD

**Issue by vunguyentuan** [dmfrancisco/JS.coach#492]
npm: https://www.npmjs.com/package/react-virtual-slider
github: https://github.com/vunguyentuan/react-virtual-slider/

**Comment by Lxxyx** [comment]
npm: https://www.npmjs.com/package/react-native-dynamic-stylesheet
github: https://github.com/Lxxyx/react-native-dynamic-stylesheet

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/react-virtual-slider
