### ISSUE TITLE
react-native-android-shimmer

### ISSUE THREAD

**Issue by ibrahimahmed-io** [dmfrancisco/JS.coach#508]
Simple shimmering effect for android in React Native. Based on [Shimmer](https://github.com/facebook/shimmer-android).

[GIT: https://github.com/Ibrahim-GHub/react-native-android-shimmer](https://github.com/Ibrahim-GHub/react-native-android-shimmer)
[NPM: https://www.npmjs.com/package/react-native-android-shimmer](https://www.npmjs.com/package/react-native-android-shimmer)

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-android-shimmer
