### ISSUE TITLE
react-native-android-circular-reveal

### ISSUE THREAD

**Issue by ibrahimahmed-io** [dmfrancisco/JS.coach#514]
A circular reveal component for android in React Native. Based on [Circular Reveal](https://github.com/ozodrukh/CircularReveal).

[GIT: https://github.com/Ibrahim-GHub/react-native-android-circular-reveal](https://github.com/Ibrahim-GHub/react-native-android-circular-reveal)
[NPM: https://www.npmjs.com/package/react-native-android-circular-reveal](https://www.npmjs.com/package/react-native-android-circular-reveal)

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-android-circular-reveal
