### ISSUE TITLE
react-native-fused-location

### ISSUE THREAD

**Issue by MustansirZia** [dmfrancisco/JS.coach#519]
https://www.npmjs.com/package/react-native-fused-location
https://github.com/MustansirZia/react-native-fused-location

I just wrote this package for react-native. It gets the most accurate location in Android devices using the new Fused API. Do you mind putting it in? :)

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-fused-location

**Comment by MustansirZia** [comment]
@dmfrancisco Thanks! :)
