### ISSUE TITLE
react-native-simple-dialogs

### ISSUE THREAD

**Issue by douglasjunior** [dmfrancisco/JS.coach#525]
Cross-platform simple dialogs for React Native based on the Modal component.

github: https://github.com/douglasjunior/react-native-simple-dialogs
npm: https://www.npmjs.com/package/react-native-simple-dialogs

### Android
<img src='https://raw.githubusercontent.com/douglasjunior/react-native-simple-dialogs/master/screenshots/android-dialog.png' width='250' /> <img src='https://raw.githubusercontent.com/douglasjunior/react-native-simple-dialogs/master/screenshots/android-progress.png' width='250' />

### iOS
<img src='https://raw.githubusercontent.com/douglasjunior/react-native-simple-dialogs/master/screenshots/ios-dialog.png' width='250' /> <img src='https://raw.githubusercontent.com/douglasjunior/react-native-simple-dialogs/master/screenshots/ios-progress.png' width='250' />

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-simple-dialogs
