### ISSUE TITLE
react-native-keyboard-manager

### ISSUE THREAD

**Issue by douglasjunior** [dmfrancisco/JS.coach#529]
Library that allows to prevent issues of keyboard sliding up and cover on React-Native iOS projects.

Github: https://github.com/douglasjunior/react-native-keyboard-manager
Npm: https://www.npmjs.com/package/react-native-keyboard-manager

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-keyboard-manager
