### ISSUE TITLE
No update since 2 weeks ago

### ISSUE THREAD

**Issue by valinaga** [dmfrancisco/JS.coach#545]
Any updates? Last update was like 15 days ago.
Thanks

**Comment by dmfrancisco** [comment]
The jobs that update metadata and readmes run hourly but unfortunately have been failing. I maintain this on my free time and so it may take some time before I can get to it. If you need more frequent updates I suggest you run your [own instance](https://github.com/dmfrancisco/JS.coach/tree/master/project) or use an alternative website such as [Yarn](https://yarnpkg.com/en/packages) or [Libraries.io](https://libraries.io/).

**Comment by dmfrancisco** [comment]
I just took a quick look and it seems that the APIs that we use to retrieve new data (such as [this](https://registry.npmjs.org/-/all)) have stopped being supported. Regarding the hourly updates, it seems the machine is running out of memory. It's a small machine but that's what the ads can cover right now. I'll spend some time figuring out next steps whenever possible.

**Comment by dmfrancisco** [comment]
The blog about this: http://blog.npmjs.org/post/157615772423/deprecating-the-all-registry-endpoint
