### ISSUE TITLE
react-instantsearch

### ISSUE THREAD

**Issue by Haroenv** [dmfrancisco/JS.coach#546]
https://yarn.fyi/react-instantsearch

Works in React and React-Native

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/react-instantsearch

**Comment by Haroenv** [comment]
By the way, we could talk to have Algolia search on the website, would be a nice improvement compared to the current search IMHO 😄

**Comment by dmfrancisco** [comment]
Yes, you're completely right! 😄  We even already have a [free account](https://github.com/madebyform/react-parts/issues/11#issuecomment-174293387) that you offered  us. It's an [open issue](https://github.com/dmfrancisco/JS.coach/issues/15) since February 2016 😅
