### ISSUE TITLE
ToggleBoxStyle not found

### ISSUE THREAD

**Issue by Abdul-majid-ashrafi** [dmfrancisco/JS.coach#549]
**Please improv** 
`import styles from './ToggleBoxStyle'`
  to 
`import styles from './ToggleBoxStyles'
` 

>  in ToggleBox.js

**Comment by dmfrancisco** [comment]
I'm not sure I understood correctly, but this seems to be an issue in one of the packages. READMEs are fetched from GitHub, so opening an issue on the package's GitHub page is preferable. Thank you for your feedback 👍
