### ISSUE TITLE
Adding chromelog for react-native

### ISSUE THREAD

**Issue by kapv89** [dmfrancisco/JS.coach#55]
Hello, I propose to add a package : chromelog(~~1.0.0~~ 1.0.1). Something to show `console.log` like dumps in chrome console from react-native without Debugging in chrome.
Thanks

**Comment by dmfrancisco** [comment]
Hello @kapv89, can you provide the link to the GitHub repository?

**Comment by kapv89** [comment]
Hi, bumped the version to 1.01, and added repository field in the package. You can check it out here: https://github.com/fractaltech/chromelog

**Comment by dmfrancisco** [comment]
Thanks @kapv89! :+1: https://js.coach/react-native/chromelog
