### ISSUE TITLE
react-native-unified-contacts

### ISSUE THREAD

**Issue by joshuapinter** [dmfrancisco/JS.coach#56]
![react-native-unified-contacts-logo](https://cloud.githubusercontent.com/assets/180819/14367872/9a25b7b8-fcd7-11e5-8861-a0b46ce75c70.png)

Your best friend when working with the latest and greatest Contacts Framework in iOS 9+ in React Native.

iOS Only at this point.

**Comment by dmfrancisco** [comment]
Thanks @joshuapinter! :+1: https://js.coach/react-native/react-native-unified-contacts

**Comment by joshuapinter** [comment]
:+1: Thanks!
