### ISSUE TITLE
Updating libraries.

### ISSUE THREAD

**Issue by MustansirZia** [dmfrancisco/JS.coach#562]
Hi!
I was wondering if you ever update your js packages for stars and installs. It looks like the stars and installs on a lot of libraries just remain the same.

**Comment by dmfrancisco** [comment]
Yes, stars and installs are updated on a daily basis. Because there are a lot of packages it may take some days for a specific package to be updated.

**Comment by MustansirZia** [comment]
Well, my package hasn't been updated since a few months. :(
https://js.coach/react-native/react-native-fused-location?search=location

**Comment by dmfrancisco** [comment]
Indeed, I can see it hasn't been updated since June 25. I'll take a closer look to check what's going on. Thanks for reporting 👍

**Comment by MustansirZia** [comment]
@dmfrancisco Thank You so much to you too! :)

**Comment by dmfrancisco** [comment]
This has finally been fixed. Sorry for the wait and thank you for the feedback 🙌

**Comment by MustansirZia** [comment]
@dmfrancisco Wonderful! Thank you so much for this amazing resource.
