### ISSUE TITLE
New Package

### ISSUE THREAD

**Issue by Durgaprasad-Budhwani** [dmfrancisco/JS.coach#563]
Hi Team,

Thanks for awesome js.coach work.

Please add below package to your catalog system.
[Active Directory Authentication Library (ADAL) plugin for React Native apps](https://github.com/Durgaprasad-Budhwani/azure-activedirectory-library-for-react-native)

Description:
Active Directory Authentication Library (ADAL) plugin provides easy to use authentication functionality for your React Native apps by taking advantage of Windows Server Active Directory and Windows Azure Active Directory.

Please let me know if you need any other information.

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-azure-adal

Sorry for taking so long to add your package.
