### ISSUE TITLE
react-photo-layout-editor

### ISSUE THREAD

**Issue by redgoose-dev** [dmfrancisco/JS.coach#566]
Hi!

This is a block layout editor from react.

Please add my package to JS.coach.

GitHub : https://github.com/RedgooseDev/react-photo-layout-editor
npmjs : https://www.npmjs.com/package/react-photo-layout-editor

**Comment by dmfrancisco** [comment]
Thanks and sorry for the wait :+1: https://js.coach/react/react-photo-layout-editor

**Comment by RedgooseDev** [comment]
Thanks!!!
