### ISSUE TITLE
react-native-appirater

### ISSUE THREAD

**Issue by ericraio** [dmfrancisco/JS.coach#58]

**Comment by dmfrancisco** [comment]
Are you sure this is the name of the package? I still can't find it on NPM: https://www.npmjs.com/package/react-native-appirater

**Comment by ericraio** [comment]
@dmfrancisco I contacted the package owner to publish the package on npm, i'll follow up again.

**Comment by ericraio** [comment]
@dmfrancisco the package has been updated to npm :)

**Comment by dmfrancisco** [comment]
Great, thank you! :+1: https://js.coach/react-native/react-native-appirater
