### ISSUE TITLE
react-native-offline

### ISSUE THREAD

**Issue by dk0r** [dmfrancisco/JS.coach#580]
**git**: [https://github.com/rauliyohmc/react-native-offline](https://github.com/rauliyohmc/react-native-offline)
**npm**: [https://www.npmjs.com/package/react-native-offline](https://www.npmjs.com/package/react-native-offline)

**Comment by dmfrancisco** [comment]
Thanks and sorry for the wait :+1: https://js.coach/react-native/react-native-offline
