### ISSUE TITLE
@opuscapita/react-dates

### ISSUE THREAD

**Issue by kvolkovich-sc** [dmfrancisco/JS.coach#587]
npm: https://www.npmjs.com/package/@opuscapita/react-dates
github: https://github.com/OpusCapita/react-dates
demo: https://opuscapita.github.io/react-dates/

**Comment by dmfrancisco** [comment]
Sorry for taking so long but we didn't support scoped packages until recently. Thank you for your contribution 👍 https://js.coach/react/@opuscapita-react-dates
