### ISSUE TITLE
@opuscapita/react-showroom-client

### ISSUE THREAD

**Issue by kvolkovich-sc** [dmfrancisco/JS.coach#588]
npm: https://www.npmjs.com/package/@opuscapita/react-showroom-client
github: https://github.com/OpusCapita/react-showroom-client

**Comment by dmfrancisco** [comment]
Sorry for taking so long but we didn't support scoped packages until recently. Thank you for your contribution 👍 https://js.coach/react/@opuscapita-react-showroom-client
