### ISSUE TITLE
@Exilz/react-native-offline-api

### ISSUE THREAD

**Issue by Exilz** [dmfrancisco/JS.coach#589]
npm: [npmjs.com/package/react-native-offline-api](npmjs.com/package/react-native-offline-api)
github: [https://github.com/Exilz/react-native-offline-api](https://github.com/Exilz/react-native-offline-api)

**Comment by dmfrancisco** [comment]
Sorry for taking so long but we didn't support scoped packages until recently, and by the title of this issue I thought this was a scoped package.

Thank you for your contribution 👍 https://js.coach/react-native/react-native-offline-api
