### ISSUE TITLE
react-virtualized-pivot

### ISSUE THREAD

**Issue by turnerniles** [dmfrancisco/JS.coach#592]
A pivot table component for React.
npm: https://www.npmjs.com/package/react-virtualized-pivot
github: https://github.com/turnerniles/react-virtualized-pivot
demo: https://turnerniles.github.io/react-virtualized-pivot

![image](https://user-images.githubusercontent.com/8146241/29742823-06c2adf8-8a54-11e7-96ed-18466e853482.gif)

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/react-virtualized-pivot
