### ISSUE TITLE
react-data-menu

### ISSUE THREAD

**Issue by dkozar** [dmfrancisco/JS.coach#593]
- Smart data-driven menu rendered in an overlay.
- Hints-based aligning with custom renderers and factories.
- Never clipped by other components or screen edges.

Github: https://github.com/dkozar/react-data-menu
NPM: https://www.npmjs.com/package/react-data-menu
Demo: http://dkozar.github.io/react-data-menu/

**Comment by dmfrancisco** [comment]
Thanks 👍  https://js.coach/react/react-data-menu
