### ISSUE TITLE
react-native-schedule-sms

### ISSUE THREAD

**Issue by ajaysaini-sgvu** [dmfrancisco/JS.coach#594]
A react native package to schedule SMS at specific dates on android platform.

Github: https://github.com/ajaysaini-sgvu/react-native-schedule-sms
NPM: https://www.npmjs.com/package/react-native-schedule-sms
Demo: https://github.com/ajaysaini-sgvu/react-native-schedule-sms/tree/master/SchduleSMSDemo

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-schedule-sms

Sorry for taking so long to get back to you.

**Comment by ajaysaini-sgvu** [comment]
Thank you @dmfrancisco :)
