### ISSUE TITLE
react-native-message-bar has moved

### ISSUE THREAD

**Issue by holyxiaoxin** [dmfrancisco/JS.coach#596]
Old repo: https://github.com/KBLNY/react-native-message-bar
New repo: https://github.com/talor-a/react-native-message-bar

npmjs: is already updated, same.

Author has not responded to issues/PRs. Please update the package at JScoach to point to the new maintained repo. 

Checkout fork issue raised here: https://github.com/KBLNY/react-native-message-bar/issues/36 and https://github.com/KBLNY/react-native-message-bar/issues/38

**Comment by dmfrancisco** [comment]
Thanks 👍  The package has been updated: https://js.coach/react-native/react-native-message-bar
