### ISSUE TITLE
react-tiny-virtual-list

### ISSUE THREAD

**Issue by clauderic** [dmfrancisco/JS.coach#597]
A tiny but mighty 3kb list virtualization library, with zero dependencies 💪 Supports variable heights/widths, scrolling to index, and more!

Github: https://github.com/clauderic/react-tiny-virtual-list
Demo: https://clauderic.github.io/react-tiny-virtual-list/
NPM: https://www.npmjs.com/package/react-tiny-virtual-list

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react/react-tiny-virtual-list
