### ISSUE TITLE
react-sizeme - Make your React Components aware of their width and height.

### ISSUE THREAD

**Issue by ctrlplusb** [dmfrancisco/JS.coach#60]
Great util for things like responsive design.

**Github:** https://github.com/ctrlplusb/react-sizeme
**NPM:** https://www.npmjs.com/package/react-sizeme
**Demo:** https://react-sizeme-example-esbefmsitg.now.sh

**Comment by dmfrancisco** [comment]
Thanks! :+1: https://js.coach/react/react-sizeme
