### ISSUE TITLE
react-native-starter-tabbar-drawer

### ISSUE THREAD

**Issue by Maxeh** [dmfrancisco/JS.coach#600]
Starter app which includes navigation, sidemenu and a tabbar.

[https://github.com/Maxeh/react-native-starter-tabbar-drawer](https://github.com/Maxeh/react-native-starter-tabbar-drawer)

**Comment by dmfrancisco** [comment]
Hello @Maxeh! It seems the package is not published on the NPM registry (at least I couldn't find it). Unfortunately at the moment we need that to keep the data updated 😕
