### ISSUE TITLE
react-native-super-chooser

### ISSUE THREAD

**Issue by fansenze** [dmfrancisco/JS.coach#603]
### A chooser of react-native, also you can think of it as a selector😜    
github:  [https://github.com/fansenze/react-native-super-chooser](https://github.com/fansenze/react-native-super-chooser)
npm: [https://www.npmjs.com/package/react-native-super-chooser](https://www.npmjs.com/package/react-native-super-chooser)

**Comment by dmfrancisco** [comment]
Thanks :+1: And sorry for the wait! https://js.coach/react-native/react-native-super-chooser
