### ISSUE TITLE
react-native-tabbar-bottom

### ISSUE THREAD

**Issue by Maxeh** [dmfrancisco/JS.coach#604]
A bottom tabbar for react native apps:

npm: [https://www.npmjs.com/package/react-native-tabbar-bottom](https://www.npmjs.com/package/react-native-tabbar-bottom)
github: [https://github.com/Maxeh/react-native-tabbar-bottom](https://github.com/Maxeh/react-native-tabbar-bottom)

![demo1](https://user-images.githubusercontent.com/10271898/30320619-74c51c84-97b3-11e7-8d7a-a830097f3b55.gif)

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-tabbar-bottom
