### ISSUE TITLE
react-native-card-carousel

### ISSUE THREAD

**Issue by yjy5264** [dmfrancisco/JS.coach#608]
Github: [https://github.com/yjy5264/react-native-card-carousel](https://github.com/yjy5264/react-native-card-carousel)
npm: [https://www.npmjs.com/package/react-native-card-carousel](https://www.npmjs.com/package/react-native-card-carousel)

**Comment by dmfrancisco** [comment]
Thanks :+1: https://js.coach/react-native/react-native-card-carousel
