### ISSUE TITLE
react-native-pan-drawer

### ISSUE THREAD

**Issue by yjy5264** [dmfrancisco/JS.coach#609]
Github: [https://github.com/yjy5264/react-native-pan-drawer](https://github.com/yjy5264/react-native-pan-drawer)
npm: [https://www.npmjs.com/package/react-native-pan-drawer](https://www.npmjs.com/package/react-native-pan-drawer)

**Comment by dmfrancisco** [comment]
Thanks 👍  This was already in the catalog: https://js.coach/react-native/react-native-pan-drawer
