### ISSUE TITLE
react-native-snap-carousel

### ISSUE THREAD

**Issue by bd-arc** [dmfrancisco/JS.coach#614]
GitHub : [https://github.com/archriss/react-native-snap-carousel/](https://github.com/archriss/react-native-snap-carousel/)
NPM : [https://www.npmjs.com/package/react-native-snap-carousel](https://www.npmjs.com/package/react-native-snap-carousel)

> You've already published the plugin, but since it has been greatly enhanced during the past few months, an update might be good ;-)

**Comment by dmfrancisco** [comment]
Done 👍  https://js.coach/react-native/react-native-snap-carousel
