### ISSUE TITLE
@zeecoder/postcss-container-query

### ISSUE THREAD

**Issue by ZeeCoder** [dmfrancisco/JS.coach#618]
It's part of a monorepo: https://github.com/ZeeCoder/container-query

**Comment by dmfrancisco** [comment]
Sorry for taking so long but we didn't support scoped packages until recently. Thank you for your contribution 👍 https://js.coach/postcss/@zeecoder-postcss-container-query

**Comment by ZeeCoder** [comment]
no worries, thanks 👍
