### ISSUE TITLE
react-lazy-hero

### ISSUE THREAD

**Issue by danistefanovic** [dmfrancisco/JS.coach#619]
Npm: https://www.npmjs.com/package/react-lazy-hero
GitHub: https://github.com/danistefanovic/react-lazy-hero
Demo: http://react-lazy-hero.danielstefanovic.com/

**Comment by dmfrancisco** [comment]
Thanks :+1: And sorry for the wait! https://js.coach/react/react-lazy-hero

**Comment by danistefanovic** [comment]
No worries. Thanks! 🍻
