### ISSUE TITLE
react-native-render-html

### ISSUE THREAD

**Issue by Exilz** [dmfrancisco/JS.coach#625]
GitHub : https://github.com/archriss/react-native-render-html
Npm : http://npmjs.com/package/react-native-render-html

This package is actually already displayed on js.coach but is never updated because it has been moved from my account to Archriss' organization.

Could you update it, please ?

**Comment by dmfrancisco** [comment]
Sure, sorry for taking so long to reply. It should be good now! https://js.coach/react-native/react-native-render-html

**Comment by Exilz** [comment]
Fantastic, thank you.
