### ISSUE TITLE
react-with-separator

### ISSUE THREAD

**Issue by albinekb** [dmfrancisco/JS.coach#628]
npm: https://www.npmjs.com/package/react-with-separator
github: https://github.com/LinusU/react-with-separator

**Comment by dmfrancisco** [comment]
Thanks :+1: And sorry for the wait! https://js.coach/react/react-with-separator

**Comment by albinekb** [comment]
Thanks! I'm loving js.coach 😍  Helps a lot in the jungle of react components 👍

**Comment by LinusU** [comment]
Awesome 🎉 🌮
