### ISSUE TITLE
react-moment-input

### ISSUE THREAD

**Issue by SymphonyKenanBerbic** [dmfrancisco/JS.coach#630]
npm: https://www.npmjs.com/package/react-moment-input
bitbucket: https://git@bitbucket.org/kenanberbic/react-moment-input

Thanks.

**Comment by dmfrancisco** [comment]
Hello! Sorry for taking so long to reply.

Unfortunately we currently rely on GitHub to extract some metadata, and your package is on Bitbucket. I would love to support Bitbucket but it's unlikely that integration will be implemented soon 😕  Sorry about that.
