### ISSUE TITLE
react-native-prompt-simple

### ISSUE THREAD

**Issue by kimvex** [dmfrancisco/JS.coach#639]
Github: [https://github.com/kimvex/react-native-prompt-simple](https://github.com/kimvex/react-native-prompt-simple)
NPM: [https://www.npmjs.com/package/react-native-prompt-simple](https://www.npmjs.com/package/react-native-prompt-simple)

**Comment by dmfrancisco** [comment]
Thanks :+1: And sorry for the wait! https://js.coach/react-native/react-native-prompt-simple
