### ISSUE TITLE
react-native-underline-tabbar

### ISSUE THREAD

**Issue by Slowyn** [dmfrancisco/JS.coach#643]
GitHub : https://github.com/Slowyn/react-native-underline-tabbar
NPM : https://www.npmjs.com/package/react-native-underline-tabbar

> You've already published the plugin, but since it has been greatly enhanced during the past few months, an update might be good ;-)

**Comment by dmfrancisco** [comment]
Sure 👍  I just updated it: https://js.coach/react-native/react-native-underline-tabbar
