### ISSUE TITLE
Update react-native-parallax-scroll link 

### ISSUE THREAD

**Issue by z4o4z** [dmfrancisco/JS.coach#644]
New repo: https://github.com/monterosalondon/react-native-parallax-scroll
New npm: https://www.npmjs.com/package/@monterosa/react-native-parallax-scroll

**Comment by dmfrancisco** [comment]
Hi, it should be good now: https://js.coach/react-native/react-native-parallax-scroll

**Comment by dmfrancisco** [comment]
Well, unfortunately we don't support scoped packages yet, so that's why it still says "updated 5 months ago", because it's referring to the `react-native-parallax-scroll` package. But the README at least is now updated correctly.

**Comment by dmfrancisco** [comment]
This is now supported and has been updated:
https://js.coach/react-native/@monterosa-react-native-parallax-scroll

Thanks 👍
