### ISSUE TITLE
@inteach/react-native-scroll-indicator

### ISSUE THREAD

**Issue by alexandre-garrec** [dmfrancisco/JS.coach#651]
https://github.com/InTeach/react-native-scroll-indicator
https://www.npmjs.com/package/@inteach/react-native-scroll-indicator

**Comment by dmfrancisco** [comment]
Sorry for taking so long but we didn't support scoped packages until recently. Thank you for your contribution 👍 https://js.coach/react-native/@inteach-react-native-scroll-indicator
