### ISSUE TITLE
redux-easy-connect

### ISSUE THREAD

**Issue by SymphonyKenanBerbic** [dmfrancisco/JS.coach#653]
npm: https://www.npmjs.com/package/redux-easy-connect
bitbucket: https://bitbucket.org/kenanberbic/redux-easy-connect

Thanks.

**Comment by dmfrancisco** [comment]
Hello! Sorry for taking so long to reply.

Unfortunately we currently rely on GitHub to extract some metadata, and your package is on Bitbucket. I would love to support Bitbucket but it's unlikely that integration will be implemented soon 😕  Sorry about that.
