### ISSUE TITLE
next-express-bootstrap-boilerplate

### ISSUE THREAD

**Issue by MustansirZia** [dmfrancisco/JS.coach#659]
Hi guys at js.coach!
Would you be kind enough to add my repository to the react section? That'd be really wonderfull.
:) 
It's a boilerplate/starter kit for React.js, Next.js, Express.js, react-bootstrap and SCSS. 

https://github.com/MustansirZia/next-express-bootstrap-boilerplate

**Comment by dmfrancisco** [comment]
Hello! Looks interesting 👍 The system requires the package to be both on GitHub and NPM, but I wasn't able to find it on NPM: https://www.npmjs.com/package/next-express-bootstrap-boilerplate

Do you think you could publish it there?

**Comment by MustansirZia** [comment]
@dmfrancisco Surely! :) Published the package to [npm](https://www.npmjs.com/package/next-express-bootstrap-boilerplate) as a CLI tool that'll clone the boilerplate. 
Please take a look again.

**Comment by dmfrancisco** [comment]
Looking good! Thanks 👍 https://js.coach/react/next-express-bootstrap-boilerplate

**Comment by MustansirZia** [comment]
Thank you to you too!
