### ISSUE TITLE
Add React Native: Android App Tour Library

### ISSUE THREAD

**Issue by prscX** [dmfrancisco/JS.coach#666]
Hi,

I have created a React Native bridge plugin for KeepSafe/TapTargetView. It allow users to provide App Tour. Can you please add below npm node to your React Native packages list:

Node Name: react-native-taptargetview
Link: https://github.com/prscX/react-native-taptargetview

Please let me know in case any discuss is required for the same

Thanks
Pranav

**Comment by dmfrancisco** [comment]
Sure, thanks! 👍  https://js.coach/react-native/react-native-taptargetview
