### ISSUE TITLE
Components no longer appear on the right pane

### ISSUE THREAD

**Issue by jbrodriguez** [dmfrancisco/JS.coach#667]
I used to be able to preview components on the right pane, but this no longer seems to work.

Clicking on a component opens github on the same tab 😞 

Is this something you're willing to bring back ?

**Comment by dmfrancisco** [comment]
That's strange 😕 For me I still have the same behavior. Which browser are you using?

**Comment by dmfrancisco** [comment]
I just restarted the server, because I was seeing different hashes for the JavaScript files which could cause the issue you reported. Let me know if it's working for you now please.

Thank you for reporting 💪

**Comment by jbrodriguez** [comment]
Yes, it's working now ! Awesome site, thanks a lot !
