### ISSUE TITLE
Add React Native: iOS App Tour Library

### ISSUE THREAD

**Issue by prscX** [dmfrancisco/JS.coach#673]
Hi,

I have created a React Native bridge plugin for aromajoin/material-showcase-ios. It allow users to provide App Tour. Can you please add below npm node to your React Native packages list:

Node Name: react-native-material-showcase-ios
Link: https://github.com/prscX/react-native-material-showcase-ios

Please let me know in case any discuss is required for the same

Thanks
Pranav

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-material-showcase-ios
Also opened a PR to add the `repository` field to your package.json file 🙂
