### ISSUE TITLE
Halfcard Library for React Native

### ISSUE THREAD

**Issue by chethann** [dmfrancisco/JS.coach#674]
Halfcard for React Native. A flexible Halfcard component for React native with callbacks and adjustable slide duration!
Github: https://github.com/chethann/rn-halfcard
NPM Package name: rn-halfcard

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/rn-halfcard

**Comment by chethann** [comment]
Thank you @dmfrancisco
