### ISSUE TITLE
react-native-gpuimage

### ISSUE THREAD

**Issue by CubeSugar** [dmfrancisco/JS.coach#682]
Hi guys at js.coach!
Would you be kind enough to add my repository to the react native section?
That'd be really wonderfull.

react-native-gpuimage
npm:  https://www.npmjs.com/package/wj-react-native-gpuimage
GitHub: https://github.com/CubeSugar/react-native-GPUImage

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/wj-react-native-gpuimage
