### ISSUE TITLE
add npm package - @ssv/signalr-client

### ISSUE THREAD

**Issue by claylaut** [dmfrancisco/JS.coach#686]
I believe the following package should be added:
> NPM package name 

@ssv/signalr-client
https://www.npmjs.com/package/@ssv/signalr-client

Thanks a lot

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/@ssv/signalr-client

**Comment by claylaut** [comment]
@dmfrancisco thanks mate :)
