### ISSUE TITLE
react-modern-library-boilerplate

### ISSUE THREAD

**Issue by transitive-bullshit** [dmfrancisco/JS.coach#690]
I believe the following package should be added:
> [react-modern-library-boilerplate](https://www.npmjs.com/package/react-modern-library-boilerplate)

**Comment by dmfrancisco** [comment]
> Note: Modern means modern as of November, 2017.. I'm sure everything will change in a month..

Ahah 😂  Thanks, just added your package here: https://js.coach/react-modern-library-boilerplate
