### ISSUE TITLE
react-native-buttonex

### ISSUE THREAD

**Issue by Noitidart** [dmfrancisco/JS.coach#691]
I believe the following package should be added:
> npm i react-native-buttonex

https://github.com/Noitidart/react-native-buttonex

https://www.npmjs.com/package/react-native-buttonex

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-buttonex

**Comment by Noitidart** [comment]
Thank you @dmfrancisco!! :)
