### ISSUE TITLE
react-native-app-intro-slider

### ISSUE THREAD

**Issue by Jacse** [dmfrancisco/JS.coach#694]
I believe the following package should be added:
> react-native-app-intro-slider

[Github](https://github.com/Jacse/react-native-app-intro-slider)
[NPM](https://www.npmjs.com/package/react-native-app-intro-slider)

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-app-intro-slider

**Comment by Jacse** [comment]
Cool, cheers!
