### ISSUE TITLE
Please add https://github.com/ananddayalan/nextjs-in-firebase-with-bootstrap

### ISSUE THREAD

**Issue by ananddayalan** [dmfrancisco/JS.coach#695]
I believe the following package should be added:
> https://github.com/ananddayalan/nextjs-in-firebase-with-bootstrap

**Comment by dmfrancisco** [comment]
Thanks for your contribution 👍  Right now [we need packages to be published on the NPM registry](https://github.com/jscoach/support/blob/master/CONTRIBUTING.md#what-if-the-package-is-private--not-published-on-the-npm-registry) in order to add them to the catalog. Do you think you can publish it?

**Comment by ananddayalan** [comment]
@dmfrancisco Sure. Here is the NPM package nextjs-in-firebase-with-bootstrap
NPM URL https://www.npmjs.com/package/nextjs-in-firebase-with-bootstrap

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/nextjs-in-firebase-with-bootstrap
