### ISSUE TITLE
Page resets back to top

### ISSUE THREAD

**Issue by InYourDreamz** [dmfrancisco/JS.coach#696]
Page resets back to top after clicking "Load More" and clicking on a package to show the modal.

Kinda annoying when you're browsing packages. Anyway to retain the position instead of starting all over again?

**Comment by dmfrancisco** [comment]
@InYourDreamz Can you tell me which browser you are using?

**Comment by InYourDreamz** [comment]
I'm using Chrome on Mac.
Btw, it's the same on Safari as well.

**Comment by dmfrancisco** [comment]
Thank you 👍  I was able to reproduce. This is a bug, I'll take a look.

**Comment by dmfrancisco** [comment]
@InYourDreamz It should be good now, let me know if you find any issue please.
Thanks for reporting 💪
