### ISSUE TITLE
Add package rn_resolution

### ISSUE THREAD

**Issue by TerranTian** [dmfrancisco/JS.coach#698]
I believe the following package should be added:
> [rn_resolution](https://github.com/TerranTian/rn_resolution)

[https://github.com/TerranTian/rn_resolution]()

**Comment by dmfrancisco** [comment]
Thanks for your contribution 👍  Right now [we need packages to be published on the NPM registry](https://github.com/jscoach/support/blob/master/CONTRIBUTING.md#what-if-the-package-is-private--not-published-on-the-npm-registry) in order to add them to the catalog. Do you think you can publish it?
