### ISSUE TITLE
Add React Native Bridge for Native Spruce Library

### ISSUE THREAD

**Issue by prscX** [dmfrancisco/JS.coach#713]
I believe the following package should be added:
> [react-native-spruce](https://github.com/prscX/react-native-spruce)

Hi,

I have created a React Native bridge plugin for [willowtreeapps/spruce-android](https://github.com/willowtreeapps/spruce-android). It help developers to easily animate views at the appropriate time. Can you please add this npm node to your React Native packages list:

Please let me know in case any discuss is required for the same

Thanks
Pranav

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-spruce
