### ISSUE TITLE
Add simplified-promise

### ISSUE THREAD

**Issue by prscX** [dmfrancisco/JS.coach#716]
I believe the following package should be added:
> [simplified-promise](https://github.com/prscX/simplified-promise)

Hi,

I have created a JavaScript package for using JavaScript Promise in a simplified way. Can you please add this npm node to your JavaScript packages list

Please let me know in case any discussion is required for the same

Thanks
Pranav

**Comment by dmfrancisco** [comment]
Thank you for your contribution! I haven't added the package to the catalog yet simply because it doesn't seem to match well our current collections. I'll tag the issue so we can add it back later 👍
