### ISSUE TITLE
Add @lahzenegar/react-checkbox-group

### ISSUE THREAD

**Issue by FarzadKarkhani** [dmfrancisco/JS.coach#717]
I believe the following package should be added:
[@lahzenegar/react-checkbox-group](https://www.npmjs.com/package/@lahzenegar/react-checkbox-group)

**Comment by dmfrancisco** [comment]
Thank you for your contribution 👍 Sorry for taking so long, we usually don't add forks but I just published it in the catalog: https://js.coach/@lahzenegar/react-checkbox-group
