### ISSUE TITLE
Add react-nice-input-password

### ISSUE THREAD

**Issue by renanborgez** [dmfrancisco/JS.coach#722]
I believe the following package should be added:
> [react-nice-input-password](https://github.com/renanborgez/react-nice-input-password)

---

I've created a component do simply the way that we calculate de strenght of password, now we can have a pre-configurated input-password with strengh bar passing simple parameters to measure it

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-nice-input-password
