### ISSUE TITLE
react-native-play-sound

### ISSUE THREAD

**Issue by ghitatomy** [dmfrancisco/JS.coach#724]
I believe the following package should be added:
> NPM package name

✂️ _Please remove the following sections and this line from your issue. Thank you for contributing!_

---

A few frequently asked questions:

**What if the package is private / not published on the NPM registry?**

We currently rely on the NPM registry to list packages. But please open this issue anyway. We'll tag it accordingly and keep track of it.

**What if the package's source is not hosted on GitHub?**

We currently rely on GitHub to retrieve an updated README and stars. But please open this issue anyway and if another git hosting service is frequently asked, we'll consider supporting it.

**What if the `package.json` file doesn't include a link to GitHub?**

If this is your own package, please consider filling the `repository` field of your `package.json` file. You can read more information on this page: https://docs.npmjs.com/files/package.json#repository

If this is not your package, please include a GitHub link in this issue.

**What if the package doesn't fit in any of the existing collections?**

If this package is not about React, Babel or any of the other available collections, please open this issue anyway. We'll tag it accordingly so we can check it if we decide to expand the catalog.

---

Other recommended actions besides creating this issue:

**If the package is a PostCSS plugin:**

Consider also opening a PR here: https://github.com/himynameisdave/postcss-plugins#submitting-a-new-plugin This community project defines a set of categories that we also use in this catalog.

**If the package is compatible with React Native:**

Consider also opening a PR here: https://github.com/react-community/native-directory#how-do-i-add-a-library We're adding the "works without detaching an Expo application" flag to this catalog.

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-play-sound
