### ISSUE TITLE
Add React Native Bridge for Native Iconic Button Library

### ISSUE THREAD

**Issue by prscX** [dmfrancisco/JS.coach#727]
I believe the following package should be added:
> [react-native-iconic](https://github.com/prscX/react-native-iconic)

Hi,

I have created a React Native bridge plugin for [victorBaro/VBFPopFlatButton](https://github.com/victorBaro/VBFPopFlatButton) & [balysv/material-menu](https://github.com/balysv/material-menu). Can you please add this npm node to your React Native packages list:

Please let me know in case any discuss is required for the same

Thanks
Pranav

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-iconic
