### ISSUE TITLE
Add React Native Bridge for Native Download Button Library

### ISSUE THREAD

**Issue by prscX** [dmfrancisco/JS.coach#728]
I believe the following package should be added:
> [react-native-download-button](https://github.com/prscX/react-native-download-button)

Hi,

I have created a React Native bridge plugin for [fenjuly/ArrowDownloadButton](https://github.com/fenjuly/ArrowDownloadButton) & [elbryan/FFCircularProgressView](https://github.com/elbryan/FFCircularProgressView). Can you please add this npm node to your React Native packages list:

Please let me know in case any discuss is required for the same

Thanks
Pranav

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-download-button
