### ISSUE TITLE
Add React Native Bridge for Native Bottom Sheet Library

### ISSUE THREAD

**Issue by prscX** [dmfrancisco/JS.coach#734]
I believe the following package should be added:
> [react-native-bottom-action-sheet](https://github.com/prscX/react-native-bottom-action-sheet)

Hi,

I have created a React Native bridge plugin for Bottom Sheets. Can you please add this npm node to your React Native packages list.

Please let me know in case any discuss is required for the same

Thanks
Pranav

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-bottom-action-sheet
