### ISSUE TITLE
Add React Native Bridge for Native Popover Library

### ISSUE THREAD

**Issue by prscX** [dmfrancisco/JS.coach#735]
I believe the following package should be added:
> [react-native-popover-menu](https://github.com/prscX/react-native-popover-menu)

I have created a React Native bridge plugin for native popover. Can you please add this npm node to your React Native packages list.

Please let me know in case any discuss is required for the same.

Thanks
Pranav

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-popover-menu
