### ISSUE TITLE
refresh cache

### ISSUE THREAD

**Issue by magicismight** [dmfrancisco/JS.coach#74]
The npm package `react-native-svg` have been moved to https://github.com/magicismight/react-native-art-svg.
But the preview page is the expired one.

**Comment by dmfrancisco** [comment]
@magicismight Thank you. Has the preview page been updated in the meantime?

**Comment by magicismight** [comment]
It has been updated on js.coach after about 2 days since it has been changed in npm.

**Comment by dmfrancisco** [comment]
I see. Thank you for reporting!
