### ISSUE TITLE
Add webpack-api-mocker

### ISSUE THREAD

**Issue by jaywcjlove** [dmfrancisco/JS.coach#740]
I believe the following package should be added:
> webpack-api-mocker

https://www.npmjs.com/package/webpack-api-mocker

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/webpack-api-mocker

Please consider setting the `repository` field in your `package.json` file, so that people and machines can find your project's GitHub page more easily 🙂

**Comment by jaywcjlove** [comment]
👌 @dmfrancisco
