### ISSUE TITLE
add react-navigation-props-mapper and react-navigation-props-mapper

### ISSUE THREAD

**Issue by vonovak** [dmfrancisco/JS.coach#742]
I believe the following packages should be added:
> [react-navigation-props-mapper](https://www.npmjs.com/package/react-navigation-header-buttons)

 and 

>[react-navigation-header-buttons](https://www.npmjs.com/package/react-navigation-header-buttons)

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here:
https://js.coach/react-navigation-props-mapper
https://js.coach/react-navigation-header-buttons
