### ISSUE TITLE
react-native-picker-select

### ISSUE THREAD

**Issue by lfkwtz** [dmfrancisco/JS.coach#743]
I believe the following package should be added:
> react-native-picker-select

https://www.npmjs.com/package/react-native-picker-select

**Comment by danceyoung** [comment]
Hi,why my demo gif don' t show in npm

**Comment by dmfrancisco** [comment]
@danceyoung Regarding #741, it seems to be working now 👍

**Comment by dmfrancisco** [comment]
@lfkwtz Thanks :+1: Just added your package here: https://js.coach/react-native-picker-select
