### ISSUE TITLE
Add @mobiscroll/react-lite

### ISSUE THREAD

**Issue by dioslaska** [dmfrancisco/JS.coach#752]
I believe the following package should be added:
> @mobiscroll/react-lite

The [mobiscroll-react](https://www.npmjs.com/package/mobiscroll-react) package has been renamed to [@mobiscroll/react-lite](https://www.npmjs.com/package/@mobiscroll/react-lite), so would be good to remove the old one.

Thanks!

**Comment by dmfrancisco** [comment]
Thanks :+1: Just made that change: https://js.coach/@mobiscroll/react-lite
