### ISSUE TITLE
Add @rcaferati/react-native-really-awesome-button

### ISSUE THREAD

**Issue by rcaferati** [dmfrancisco/JS.coach#753]
I believe the following package should be added:
[react-native-really-awesome-button](https://www.npmjs.com/package/react-native-really-awesome-button)

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-really-awesome-button

**Comment by rcaferati** [comment]
@dmfrancisco Thank you! 👍
