### ISSUE TITLE
Android only AutoCompleteTextView

### ISSUE THREAD

**Issue by Noitidart** [dmfrancisco/JS.coach#755]
I believe the following package should be added:
> autocompletetextview

This is Android only.

https://github.com/rajsuvariya/autocompletetextview

https://www.npmjs.com/package/autocompletetextview

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/autocompletetextview

**Comment by Noitidart** [comment]
Thank you @dmfrancisco ! :)
