### ISSUE TITLE
react-native-general-calendars

### ISSUE THREAD

**Issue by rghorbani** [dmfrancisco/JS.coach#757]
I believe the following package should be added:
> react-native-general-calendars
> https://github.com/rghorbani/react-native-general-calendars

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-general-calendars

Small note, the repository property seems to be incorrect:
https://github.com/rghorbani/react-native-general-calendars/blob/master/package.json#L79
