### ISSUE TITLE
React Native X Bar

### ISSUE THREAD

**Issue by harrysolovay** [dmfrancisco/JS.coach#772]
I believe the following package should be added:
> react-native-x-bar

A few frequently asked questions:

**What if the package is private / not published on the NPM registry?**
It is publicly available through the NPM registry: https://www.npmjs.com/package/react-native-x-bar

**What if the `package.json` file doesn't include a link to GitHub?**
The source includes a package.json file with the associated GitHub repository (https://github.com/harrysolovay/react-native-x-bar)

**What if the package doesn't fit in any of the existing collections?**
I believe that this package will fit into the catalogue quite well. That being said, I understand if you'd prefer not to add it (really hoping you do though––it would be great to get people using it and giving feedback). Thank you for your consideration.

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-x-bar

**Comment by harrysolovay** [comment]
Incredible! Thank you so much!!!
