### ISSUE TITLE
Request to add cp-react-tree-table

### ISSUE THREAD

**Issue by constantin-p** [dmfrancisco/JS.coach#773]
I believe the following package should be added:

`cp-react-tree-table`

---

> `cp-react-tree-table`
> A fast, efficient tree table component for ReactJS.
> https://www.npmjs.com/package/cp-react-tree-table
> Demo: https://constantin-p.github.io/cp-react-tree-table/

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/cp-react-tree-table
