### ISSUE TITLE
React-Native-WaveView

### ISSUE THREAD

**Issue by CubeSugar** [dmfrancisco/JS.coach#798]
Hi guys at js.coach!

Would you be kind enough to add my repository to the react native section?
That'd be really wonderfull.

npm: 
https://www.npmjs.com/package/react-native-waveview

GitHub: 
https://github.com/CubeSugar/react-native-waveview

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-waveview
