### ISSUE TITLE
Add react-native-super-ellipse-mask

### ISSUE THREAD

**Issue by everdrone** [dmfrancisco/JS.coach#819]
I believe the following package should be added:

`react-native-super-ellipse-mask`
[NPM](https://www.npmjs.com/package/react-native-super-ellipse-mask)
[GitHub](https://github.com/everdrone/react-native-super-ellipse-mask)

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-super-ellipse-mask
