### ISSUE TITLE
Add @foes/react-i18n-router

### ISSUE THREAD

**Issue by gorkalaucirica** [dmfrancisco/JS.coach#828]
I believe the following package should be added:
> `@foes/react-i18n-router`

**Comment by jalalazimi** [comment]
Hi @gorkalaucirica, it seems this package doesn't exist! 
I just found `https://www.npmjs.com/package/@foes/react-i18n-routing`. It already published.
Can you check it?

**Comment by gorkalaucirica** [comment]
@jalalazimi Yes! That's correct!

Thank you

**Comment by jalalazimi** [comment]
Thanks @gorkalaucirica.
