### ISSUE TITLE
responsive-watch

### ISSUE THREAD

**Issue by mrmartineau** [dmfrancisco/JS.coach#83]
https://www.npmjs.com/package/responsive-watch - Watch some media queries and react when they change

**Comment by dmfrancisco** [comment]
Thanks! 👍 https://js.coach/react/responsive-watch

**Comment by mrmartineau** [comment]
Thanks @dmfrancisco, this isn't a React-specific module, could there be a section for non-library modules? Not sure what to call it though 😰

**Comment by dmfrancisco** [comment]
@mrmartineau You are right, that's why I haven't merged the other ones you suggested just yet 😄  Since this one had a React demo and everything, I decided to tag it as a React, but a section for non-library modules would a nice addition 👍

**Comment by mrmartineau** [comment]
great, thanks @dmfrancisco
