### ISSUE TITLE
Add rechartjs

### ISSUE THREAD

**Issue by zyj1022** [dmfrancisco/JS.coach#831]
I believe the following package should be added:

> rechartjs

[https://github.com/zyj1022/rechartjs](https://github.com/zyj1022/rechartjs)

[https://www.npmjs.com/package/rechartjs](https://www.npmjs.com/package/rechartjs)

[Demo View](http://zyj1022.github.io/demos/rechartjs/)

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/rechartjs
