### ISSUE TITLE
Adding Camera Characteristics and Display Metrics

### ISSUE THREAD

**Issue by BhargavaCS** [dmfrancisco/JS.coach#838]
I believe the following package should be added:
>react-native-rear-camera-characteristics-display-metrics 

NPM Package Link : [https://www.npmjs.com/package/react-native-rear-camera-characteristics-display-metrics](url)

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-rear-camera-characteristics-display-metrics
