### ISSUE TITLE
Add @react-firebase

### ISSUE THREAD

**Issue by rakannimer** [dmfrancisco/JS.coach#849]
Hey, 

Thanks for building and maintaining this :) 

I believe the following packages should be added:
> @react-firebase/database
> @react-firebase/firestore
> @react-firebase/auth

Source code : https://github.com/rakannimer/react-firebase/

Docs : https://react-firebase-js.com

**Comment by dmfrancisco** [comment]
Thank you :+1: Just added your packages here:

- https://js.coach/@react-firebase/database
- https://js.coach/@react-firebase/firestore
- https://js.coach/@react-firebase/auth

Some notes:

- The [description in the firestore package](https://github.com/rakannimer/react-firebase-firestore/blob/master/package.json) points to the wrong repository
- Could you add the descriptions you have in the GitHub repositories to the `package.json`s too?

**Comment by rakannimer** [comment]
Thank you @dmfrancisco ! 

I updated the packages according to your notes (thanks for that !).

Cheers 😀
