### ISSUE TITLE
react-redux-loading-bar

### ISSUE THREAD

**Issue by mironov** [dmfrancisco/JS.coach#85]
https://www.npmjs.com/package/react-redux-loading-bar
https://github.com/mironov/react-redux-loading-bar

A simple React component that provides Loading Bar for long running tasks. Works out of the box with redux-promise-middleware and can be easily tweaked for other usage.

**Comment by dmfrancisco** [comment]
Thanks! 👍  https://js.coach/react/react-redux-loading-bar
