### ISSUE TITLE
Add react-native-confirmation-code-input

### ISSUE THREAD

**Issue by retyui** [dmfrancisco/JS.coach#850]
I believe the following package should be added:
> react-native-confirmation-code-input

https://github.com/retyui/react-native-confirmation-code-field
https://www.npmjs.com/package/react-native-confirmation-code-field
https://github.com/retyui/react-native-confirmation-code-field/blob/master/docs/API.md

**Comment by dmfrancisco** [comment]
Thanks :+1: Your package is already available here: https://js.coach/react-native-confirmation-code-input
