### ISSUE TITLE
is react-focustip good enough to add?

### ISSUE THREAD

**Issue by pooyarm** [dmfrancisco/JS.coach#875]
I believe the following package should be added:
> react-focustip

I just published this package recently, just wanted to share and also to know your comments and if it's good enough, it can be added.
https://www.npmjs.com/package/react-focustip

Thank you guys

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-focustip Sorry for the wait 😕
