### ISSUE TITLE
Add react-native-pure-navigation-bar

### ISSUE THREAD

**Issue by gxsshallot** [dmfrancisco/JS.coach#880]
I believe the following package should be added:
> react-native-pure-navigation-bar

Github: [https://github.com/gaoxiaosong/react-native-pure-navigation-bar](https://github.com/gaoxiaosong/react-native-pure-navigation-bar)

**Comment by dmfrancisco** [comment]
Sorry for the wait 😬 Just added this now! https://js.coach/react-native-pure-navigation-bar Thanks for submitting 👍

**Comment by gaoxiaosong** [comment]
@dmfrancisco Thanks~~~
