### ISSUE TITLE
Add react-native-general-listener

### ISSUE THREAD

**Issue by gxsshallot** [dmfrancisco/JS.coach#881]
I believe the following package should be added:
> react-native-general-listener

Github: [https://github.com/gaoxiaosong/react-native-general-listener](https://github.com/gaoxiaosong/react-native-general-listener)

**Comment by dmfrancisco** [comment]
Sorry for the wait 😬 Just added this now! https://js.coach/react-native-general-listener Thanks for submitting 👍
