### ISSUE TITLE
Add react-native-general-storage

### ISSUE THREAD

**Issue by gxsshallot** [dmfrancisco/JS.coach#882]
I believe the following package should be added:
> react-native-general-storage

Github: [https://github.com/gaoxiaosong/react-native-general-storage](https://github.com/gaoxiaosong/react-native-general-storage)

**Comment by dmfrancisco** [comment]
Sorry for the wait 😬 Just added this now! https://js.coach/react-native-general-storage Thanks for submitting 👍
