### ISSUE TITLE
Add react-native-general-actionsheet

### ISSUE THREAD

**Issue by gxsshallot** [dmfrancisco/JS.coach#883]
I believe the following package should be added:
> react-native-general-actionsheet

Github: [https://github.com/gaoxiaosong/react-native-general-actionsheet](https://github.com/gaoxiaosong/react-native-general-actionsheet)

**Comment by dmfrancisco** [comment]
Sorry for the wait 😬 Just added this now! https://js.coach/react-native-general-actionsheet Thanks for submitting 👍
