### ISSUE TITLE
Suggest new package - (react-sky)

### ISSUE THREAD

**Issue by lucagez** [dmfrancisco/JS.coach#885]
https://www.npmjs.com/package/react-sky

**Comment by dmfrancisco** [comment]
Thanks @lucagez 👍 There was an issue because the name field in the `package.json` file in the GitHub repository didn't match the one used in the published version on NPM. But it's available now here: https://js.coach/react-sky

**Comment by lucagez** [comment]
Thank you David for adding my repo to js.coach!
Bests,
Luca
