### ISSUE TITLE
Please review and add this package to jscoach

### ISSUE THREAD

**Issue by abhishekk09** [dmfrancisco/JS.coach#888]
I believe the following package should be added:
> react-native-percentage-rectangle

NPM link - https://www.npmjs.com/package/react-native-percentage-rectangle

Github link - https://github.com/abhishekk09/react-native-percentage-rectangle

![ss](https://user-images.githubusercontent.com/36265211/49938950-64715800-ff01-11e8-9d63-f004c8fa693f.png)

Please check for the screenshot attached.

Thanks

**Comment by dmfrancisco** [comment]
Thanks :+1: Just added your package here: https://js.coach/react-native-percentage-rectangle
