### ISSUE TITLE
new package react-native-easypopup

### ISSUE THREAD

**Issue by barron9** [dmfrancisco/JS.coach#904]
I believe the following package should be added:
> NPM package name
react-native-easypopup

https://github.com/barron9/react-native-easypopup

**Comment by jalalazimi** [comment]
It's not a valid package. `Package.json` does not exist as well. Check the following repository:
https://github.com/barron9/react-native-easypopup

**Comment by barron9** [comment]
if you do npm i , you will see

**Comment by barron9** [comment]
can you add now

**Comment by jalalazimi** [comment]
Thanks 👍 Just added your package here: https://js.coach/react-native-easypopup
