### ISSUE TITLE
Add React Native Pell RIch Editor

### ISSUE THREAD

**Issue by stulip** [dmfrancisco/JS.coach#910]
I believe the following package should be added:
> react-native-pell-rich-editor
[NPM](https://www.npmjs.com/package/react-native-pell-rich-editor)
[GitHub](https://github.com/stulip/react-native-pell-rich-editor)

**Comment by jalalazimi** [comment]
Thanks 👍 Just added your package here: https://js.coach/react-native-pell-rich-editor
