### ISSUE TITLE
Strange time stats

### ISSUE THREAD

**Issue by retyui** [dmfrancisco/JS.coach#913]
[NPM package react-native-orientation](https://js.coach/react-native-orientation?search=orient&collection=React+Native)

---

So, I see on js.coach next information:
![image](https://user-images.githubusercontent.com/4661784/55313032-828ea400-546f-11e9-9625-ff3e54a33771.png)

Then I open npm and see that the last update was a year ago!
![image](https://user-images.githubusercontent.com/4661784/55313072-96d2a100-546f-11e9-8276-d7dc8ced9428.png)

And github last commit `on 5 Jan 2018`
![image](https://user-images.githubusercontent.com/4661784/55313267-06e12700-5470-11e9-87e3-43a32753a371.png)

**Comment by retyui** [comment]
@jalalazimi
@dmfrancisco

**Comment by dmfrancisco** [comment]
@retyui Thanks for reporting this issue 👍Something seems wrong indeed, I'll take a look whenever possible.

**Comment by retyui** [comment]
@dmfrancisco Please fix this bag because you promote the outdated modules

**Comment by dmfrancisco** [comment]
@retyui Feel free to take a look [at the source](https://github.com/jscoach/server) and to submit a PR.
