### ISSUE TITLE
ADD react-native-time-log

### ISSUE THREAD

**Issue by neel132-zz** [dmfrancisco/JS.coach#916]
I believe the following package should be added:
> **react-native-time-log**
> [https://www.npmjs.com/package/react-native-time-log](https://www.npmjs.com/package/react-native-time-log)
>[https://github.com/neel132/react-native-time-log](https://github.com/neel132/react-native-time-log)

**Comment by jalalazimi** [comment]
Thanks 👍 Just added your package here: https://js.coach/react-native-time-log
