### ISSUE TITLE
ADD react-native-import

### ISSUE THREAD

**Issue by neel132-zz** [dmfrancisco/JS.coach#917]
I believe the following package should be added:
> **react-native-import**
> [https://www.npmjs.com/package/react-native-import](https://www.npmjs.com/package/react-native-import)
>[https://github.com/neel132/react-native-import](https://github.com/neel132/react-native-import)

**Comment by jalalazimi** [comment]
Thanks 👍 Just added your package here: https://js.coach/react-native-import
