### ISSUE TITLE
Add @astrocoders/react-native-selectable-text

### ISSUE THREAD

**Issue by fakenickels** [dmfrancisco/JS.coach#918]
I believe the following package should be added:
> [@astrocoders/react-native-selectable-text](https://github.com/Astrocoders/react-native-selectable-text/)

**Comment by jalalazimi** [comment]
Thanks 👍 Just added your package here: https://js.coach/react-native-selectable-text

**Comment by fakenickels** [comment]
hey! looks like that the name clashed with another lib
