### ISSUE TITLE
add rn-verifcode please

### ISSUE THREAD

**Issue by xcarpentier** [dmfrancisco/JS.coach#929]
I believe the following package should be added:
> rn-verifcode

**Comment by jalalazimi** [comment]
@xcarpentier Could you share the NPM and repo with me?

**Comment by xcarpentier** [comment]
@jalalazimi HI, yes sorry.
https://www.npmjs.com/package/rn-verifcode

**Comment by jalalazimi** [comment]
Thanks 👍 Just added your package here: https://js.coach/rn-verifcode
