### ISSUE TITLE
@brightleaf/elements

### ISSUE THREAD

**Issue by Kevnz** [dmfrancisco/JS.coach#943]
I believe the following package should be added:
@brightleaf/elements

A collection or react components based on the bulma css framework
https://github.com/brightleaf/elements

**Comment by Kevnz** [comment]
Still waiting for this to be added

**Comment by Kevnz** [comment]
Bump 😀

**Comment by dmfrancisco** [comment]
@Kevnz Sorry for the wait… There's code that will need to be updated due to API changes and at the moment there's no one dedicated to the project. We'll try to figure out how to move forward and we'll let share the update here.

**Comment by jalalazimi** [comment]
Thanks 👍 Just added your package here: https://js.coach/@brightleaf/elements
