### ISSUE TITLE
@brightleaf/react-hooks

### ISSUE THREAD

**Issue by Kevnz** [dmfrancisco/JS.coach#944]
I believe the following package should be added:
@brightleaf/react-hooks

A collection of react hooks
brightleaf/react-hooks

**Comment by Kevnz** [comment]
Still waiting

**Comment by Kevnz** [comment]
Bump 😀

**Comment by dmfrancisco** [comment]
@Kevnz Sorry for the wait… There's code that will need to be updated due to API changes and at the moment there's no one dedicated to the project. We'll try to figure out how to move forward and we'll let share the update here.

**Comment by Kevnz** [comment]
@dmfrancisco any details? I would be happy to help.

**Comment by jalalazimi** [comment]
Thanks 👍 Just added your package here: https://js.coach/@brightleaf/react-hooks

**Comment by dmfrancisco** [comment]
@jalalazimi Thanks 👍 

@Kevnz If you still have the time and want to help, you may be interested in what @jalalazimi is working on. There's an issue (#1006) where a beta link will be shared.
