### ISSUE TITLE
Add with-cookie

### ISSUE THREAD

**Issue by j-mendez** [dmfrancisco/JS.coach#999]
I believe the following package should be added:
> NPM package name

https://github.com/A11yWatch/with-cookie

Auto bind object properties to cookie with auto retrieval. Great for SSR dynamic pages. Easily create manage cookies without thinking about it.

**Comment by jalalazimi** [comment]
Thanks 👍 Just added your package here: https://js.coach/package/with-cookie

**Comment by j-mendez** [comment]
@jalalazimi looks like the link is broken for https://js.coach/package/with-cookie.

**Comment by jalalazimi** [comment]
@j-mendez Sorry, has resolved!
